# Generated by Django 2.2.dev20180812014849 on 2018-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180814_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='name',
            field=models.CharField(default='Asistencia', help_text='Asistencia (e.g. Science Fiction, French Poetry etc.)', max_length=200),
        ),
    ]
