# Generated by Django 2.2.dev20180812014849 on 2018-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_estudiante_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asistencia', help_text='Asistencia (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='name',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='asistencia',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='myapp.Asistencia'),
        ),
    ]
