# Generated by Django 2.2.dev20180812014849 on 2018-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180814_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='name',
            field=models.CharField(choices=[('A', 'Asistio'), ('N/A', 'No asistio')], default='A', max_length=2),
        ),
    ]
