# Generated by Django 2.2.dev20180812014849 on 2018-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180814_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['-primer_apellido']},
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='last_name',
            new_name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='assis',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='asistencia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='asistencia',
            field=models.CharField(choices=[('A', 'Asistio'), ('N/A', 'No asistio')], default='A', max_length=2),
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
