# Generated by Django 2.2.dev20180812014849 on 2018-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180814_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='segundo_apellido',
            field=models.CharField(default='Ingrese Apellidos', max_length=30),
        ),
    ]
