# Generated by Django 2.2.dev20180812014849 on 2018-08-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_estudiante_segundo_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes_octavo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Ingrese primer nombre', max_length=30)),
                ('primer_apellido', models.CharField(default='Ingrese Primer apellido', max_length=30)),
                ('segundo_apellido', models.CharField(default='Ingrese Segundo Apellido', max_length=30)),
                ('asistencia', models.CharField(choices=[('A', 'Asistio'), ('N/A', 'No asistio')], default='A', max_length=2)),
            ],
            options={
                'ordering': ['-primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_septimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Ingrese primer nombre', max_length=30)),
                ('primer_apellido', models.CharField(default='Ingrese Primer apellido', max_length=30)),
                ('segundo_apellido', models.CharField(default='Ingrese Segundo Apellido', max_length=30)),
                ('asistencia', models.CharField(choices=[('A', 'Asistio'), ('N/A', 'No asistio')], default='A', max_length=2)),
            ],
            options={
                'ordering': ['-primer_apellido'],
            },
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
