# Generated by Django 2.2.dev20180812014849 on 2018-08-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180814_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_octavo',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
