# Generated by Django 2.2.dev20180812014849 on 2018-08-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_estudiantes_octavo_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_septimo',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
