# Generated by Django 2.2.dev20180812014849 on 2018-08-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_estudiantes_septimo_due_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes_octavo',
            old_name='due_back',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='estudiantes_septimo',
            old_name='due_back',
            new_name='Fecha',
        ),
    ]
