# Generated by Django 2.2.dev20180812014849 on 2018-08-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_estudiantes_septimo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes_septimo',
            name='usuario',
        ),
    ]
