# Generated by Django 2.2.dev20180812014849 on 2018-08-15 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_remove_estudiantes_septimo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes_octavo',
            options={'ordering': ['-usuario']},
        ),
        migrations.AlterModelOptions(
            name='estudiantes_septimo',
            options={'ordering': ['-usuario']},
        ),
        migrations.RemoveField(
            model_name='estudiantes_octavo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiantes_octavo',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiantes_octavo',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiantes_septimo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiantes_septimo',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiantes_septimo',
            name='segundo_apellido',
        ),
        migrations.AddField(
            model_name='estudiantes_octavo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiantes_septimo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
