# Generated by Django 2.2.dev20180812014849 on 2018-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180815_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_septimo',
            name='nombre',
            field=models.CharField(default='Ingrese primer nombre', max_length=30),
        ),
    ]
