# Generated by Django 2.2.dev20180812014849 on 2018-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_estudiantes_septimo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_octavo',
            name='nombre',
            field=models.CharField(default='Ingrese primer nombre', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiantes_octavo',
            name='primer_apellido',
            field=models.CharField(default='Ingrese Primer apellido', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiantes_octavo',
            name='segundo_apellido',
            field=models.CharField(default='Ingrese Segundo Apellido', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiantes_septimo',
            name='primer_apellido',
            field=models.CharField(default='Ingrese Primer apellido', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiantes_septimo',
            name='segundo_apellido',
            field=models.CharField(default='Ingrese Segundo Apellido', max_length=30),
        ),
    ]
