# Generated by Django 2.2.dev20180812014849 on 2018-08-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180816_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bajas_calificaciones', models.CharField(max_length=30)),
                ('ausentismo', models.CharField(max_length=30)),
                ('falta_recursos', models.CharField(max_length=30)),
                ('problemas', models.CharField(max_length=30)),
                ('violencia', models.CharField(max_length=30)),
                ('adicciones', models.CharField(max_length=30)),
                ('Fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
