# Generated by Django 2.2.dev20180812014849 on 2019-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20190809_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='anuncios/')),
                ('Descripcion', models.CharField(default='Ingrese descripción de archivo', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='download',
            name='pdf',
            field=models.FileField(upload_to='download/'),
        ),
    ]
