# Generated by Django 2.2.dev20180812014849 on 2019-08-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20190809_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anuncios',
            new_name='Anuncio',
        ),
    ]
