# Generated by Django 2.2.dev20180812014849 on 2019-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20190809_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subir_Nocturno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='downloaddos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='download',
            new_name='Subir_Diurno',
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
    ]
